import React from 'react'
import { PageLayout } from '../components/PageLayout.jsx'
import { PixelCard } from '../components/PixelCard.jsx'
import { PixelButton } from '../components/PixelButton.jsx'
import { PixelToast } from '../components/PixelToast.jsx'
import { PixelRadio } from '../components/PixelRadio.jsx'
import { StepBar } from '../components/StepBar.jsx'
import { PixelSelect } from '../components/PixelSelect.jsx'
import { TrajectoryPointCard } from '../components/TrajectoryPointCard.jsx'
import { CelebrationImage } from '../components/CelebrationImage.jsx'
import { ResetArmButton } from '../components/ResetArmButton.jsx'
import { ConnectionStatusLabel } from '../components/ConnectionStatusLabel.jsx'
import { mediaAssets } from '../mediaAssets.js'
import '../components/TrajectoryPointCard.css'
import './AssemblyModelPageView.css'

const steps = [
  { id: 'step-1', status: 'done', position: 'first', label: '', title: 'INSTALL' },
  { id: 'step-2', status: 'done', position: 'middle', label: '', title: 'TEST' },
  { id: 'step-3', status: 'active', position: 'middle', label: '', title: 'ASSEMBLY' },
  { id: 'step-4', status: 'pending_4', position: 'last', label: '', title: 'EXECUTE' },
]

function JogAxisControl({ label, onNegative, onPositive }) {
  return (
    <div className="assembly-jog-control flex items-center">
      <button
        type="button"
        onClick={onNegative}
        className="w-10 h-9 text-[18px] flex items-center justify-center"
      >
        ‹
      </button>
      <div className="flex-1 text-center px text-[12px]">{label}</div>
      <button
        type="button"
        onClick={onPositive}
        className="w-10 h-9 text-[18px] flex items-center justify-center"
      >
        ›
      </button>
    </div>
  )
}

function CollisionHintModal({
  hintType,
  hintStep,
  showWrongAnswerToast,
  selectedOption,
  onSelectOption,
  onClose,
  onConfirm,
}) {
  const isDirectionStepOne = hintType === 'direction' && hintStep === 1
  const isDirectionStepTwo = hintType === 'direction' && hintStep === 2
  const isSingularityHint = hintType === 'singularity'
  const isWaypointHint = hintType === 'waypoint'
  const useCompactHintIllustration = isWaypointHint || isDirectionStepOne || isDirectionStepTwo
  const primaryLabel = isDirectionStepOne ? 'NEXT' : 'Confirm'
  const visual =
    isWaypointHint
      ? {
          alert: 'Collision occurred! Try to add more waypoints',
          lines: [
            'The TCP moves smoothly from one recorded point to the next',
            'With too few waypoints, the trajectory cannot avoid objects between the points',
            'collisions happen',
          ],
          illustrationTitle: 'Driving around a rock',
          caption:
            "Just like driving: when there's a big rock on the road, you adjust your route and go around it.",
        }
      : isDirectionStepOne
        ? {
            alert: 'Wrong Direction! You need to stop the robot immediately!',
            lines: [
              'Offsets are relative to the previous point, so a relative frame is required',
              'Using the base frame requires cumulative calculation',
              "If values don't match the frame, the point ends up in a different location",
            ],
            illustrationTitle: 'Two jogging styles',
            caption:
              '"Place the cup at the center of the table" and "Move the cup forward by 10 cm" may look the same - but they are defined in different reference frames.',
          }
        : isDirectionStepTwo
          ? {
              alert: 'In case of emergency, press the E-stop immediately.',
              lines: [
                <>
                  Press the <span className="assembly-emphasis-magenta">E-stop</span> button immediately
                </>,
                <>
                  The robot will <span className="assembly-emphasis-magenta">cut power and stop</span> moving
                </>,
                'After fixing the issue, restart and move it away manually',
              ],
              illustrationTitle: 'E-STOP button',
              caption:
                'When risk grows quickly, cutting power is the safest immediate action.',
            }
          : {
              alert: "The robot has reached a singularity. It can't move in this configuration.",
              lines: [
                'TCP motion is generated by robot joint movement',
                'At singularity, tiny TCP move requires extremely large joint speed',
                'Joint speed/angle limits are reached',
                'The robot loses motion capability in some direction',
              ],
              illustrationTitle: 'Stretched arm',
              caption:
                'When your arm is fully stretched, some directions become hard to move - same idea for robot singularity.',
            }
  const optionList = isSingularityHint
    ? [
        { value: 'A', label: 'A. The program crashed' },
        { value: 'B', label: 'B. The robot lost power' },
        {
          value: 'C',
          label: 'C. The robot lost motion capability in certain directions',
        },
      ]
    : isWaypointHint
      ? [
          { value: 'A', label: 'A. It replays the demonstrated path exactly' },
          {
            value: 'B',
            label: 'B. The TCP moves from one recorded point to the next smoothly, in order',
          },
          {
            value: 'C',
            label: 'C. The TCP automatically moves from the grab point to the drop point',
          },
        ]
      : isDirectionStepOne
        ? [
            { value: 'A', label: 'A. The offset value was wrong' },
            { value: 'B', label: 'B. The reference frame used for the offset was different' },
            { value: 'C', label: 'C. The robot speed was too high' },
          ]
        : [
            {
              value: 'A',
              label: 'A. Pausing may fail if communication is interrupted.',
            },
            { value: 'B', label: 'B. Pausing is slower' },
            { value: 'C', label: 'C. Pausing resets the robot' },
          ]
  const questionText =
    hintType === 'waypoint'
      ? 'Question: How does the robot follow a planned trajectory during execution?'
      : isDirectionStepOne
        ? 'Question: Why did the point move to a completely different position?'
        : isDirectionStepTwo
          ? 'Question: Why is pressing E-stop necessary instead of just pausing the program?'
          : 'Question: Why does the robot stop moving at a singularity?'
  const hintIllustrationImage = isWaypointHint
    ? mediaAssets.waypointDrivingAroundRock
    : isDirectionStepOne
      ? mediaAssets.assemblyDirectionReferenceFrame
    : isDirectionStepTwo
      ? mediaAssets.assemblyEstopButton
      : mediaAssets.assemblySingularityWarning

  return (
    <div className="assembly-hint-overlay fixed inset-0 z-50 flex items-center justify-center">
      <div className="assembly-hint-modal pixel-card soft-grid px-10 pb-10 pt-7">
        {showWrongAnswerToast && (
          <div
            className="assembly-wrong-answer-toast px text-[12px]"
            role="status"
          >
            Wrong answer
          </div>
        )}
        <div className="mb-8">
          <div className="assembly-hint-alert text-[28px] font-bold mb-6 flex items-center">
            <span className="assembly-hint-icon">
              <img
                src={mediaAssets.hintBulbIcon}
                alt=""
                className="assembly-hint-icon-image"
              />
            </span>
            {visual.alert}
          </div>

          <div
            className={`flex justify-between gap-8 ${
              useCompactHintIllustration ? 'items-stretch' : 'items-start'
            } ${isSingularityHint ? 'assembly-hint-layout--singularity' : ''}`}
          >
            <div className="flex-1">
              <div className="assembly-hint-copy text-[20px] flex flex-col items-center gap-2 text-center">
                <div>{visual.lines[0]}</div>
                <div className="assembly-hint-arrow px">↓</div>
                <div>{visual.lines[1]}</div>
                <div className="assembly-hint-arrow px">↓</div>
                <div>{visual.lines[2]}</div>
                {visual.lines[3] ? (
                  <>
                    <div className="assembly-hint-arrow px">↓</div>
                    <div>{visual.lines[3]}</div>
                  </>
                ) : null}
              </div>
            </div>

            <div
              className={`assembly-hint-illustration pixel-card soft-grid ${
                useCompactHintIllustration ? 'assembly-hint-illustration--waypoint' : ''
              } ${isSingularityHint ? 'assembly-hint-illustration--singularity' : ''}`}
            >
              <div className={`assembly-hint-illustration-body flex flex-col w-full h-full ${useCompactHintIllustration ? 'assembly-hint-illustration-body--waypoint' : ''}`}>
                <div className={`assembly-hint-illustration-media-slot overflow-hidden flex items-center justify-center mb-2 ${useCompactHintIllustration ? 'assembly-hint-illustration-media-slot--waypoint' : ''}`}>
                  <div className={`w-full h-full flex flex-col items-center justify-center text-center ${isSingularityHint ? 'assembly-singularity-illustration' : ''}`}>
                    {hintIllustrationImage && (
                      <div className="assembly-hint-waypoint-frame">
                        <img
                          src={hintIllustrationImage}
                          alt={
                            isDirectionStepTwo
                              ? 'E-stop button'
                              : isDirectionStepOne
                                ? 'Reference frame comparison'
                                : isWaypointHint
                                  ? 'Driving around a rock'
                                  : 'Robot singularity warning'
                          }
                          className="assembly-hint-waypoint-image"
                        />
                      </div>
                    )}
                    {!hintIllustrationImage && (
                      <>
                        <div className="text-[28px] mb-3">Illustration</div>
                        <div className="text-[26px]">{visual.illustrationTitle}</div>
                      </>
                    )}
                  </div>
                </div>
                <div className="assembly-hint-caption text-[13px]">
                  {visual.caption}
                </div>
              </div>
            </div>
          </div>
        </div>

        <div className="assembly-hint-divider mb-4" />

        <div className="text-[20px] mb-4 flex items-center gap-2">
          <span className="assembly-hint-question-icon">
            <img
              src={mediaAssets.hintThinkingIcon}
              alt=""
              className="assembly-hint-question-icon-image"
            />
          </span>
          {questionText}
        </div>

        <div className="space-y-3 text-[14px]">
          {optionList.map((option) => (
            <PixelRadio
              key={option.value}
              label={option.label}
              checked={selectedOption === option.value}
              onChange={() => onSelectOption(option.value)}
            />
          ))}
        </div>

        <div className="mt-8 flex gap-4">
          {!isDirectionStepTwo && (
            <PixelButton
              variant="white"
              className="px-8 py-4 text-[12px]"
              onClick={onClose}
            >
              Close
            </PixelButton>
          )}
          <PixelButton
            variant="magenta"
            className="flex-1 py-4 text-[12px]"
            onClick={onConfirm}
          >
            {primaryLabel}
          </PixelButton>
        </div>
      </div>
    </div>
  )
}

export function AssemblyModelPageView({
  stage,
  mode,
  grab,
  grabFrame,
  drop,
  dropFrame,
  waypoints,
  frameOptions,
  jogFrameOptions,
  canConfirm,
  isAssemblyRunning,
  hasCollision,
  showCollisionToast,
  showWrongAnswerToast,
  showCollisionHintModal,
  selectedCollisionOption,
  collisionHintType,
  collisionHintStep,
  showSuccessModal,
  successPrimaryLabel,
  successSubline = 'NEXT LEVEL UNLOCKED!',
  jogFrame,
  hasSingularityWarning,
  connectionInfo,
  onEnableTeach,
  onToggleMode,
  onConfirmTest,
  onNextBlock,
  onSuccessPrimaryAction,
  onTryAgainCurrentBlock,
  onOpenCollisionHint,
  onCloseCollisionHint,
  onSelectCollisionOption,
  onConfirmCollisionHint,
  onAddWaypoint,
  onRemoveWaypoint,
  onChangeGrabAxis,
  onChangeGrabFrame,
  onChangeDropAxis,
  onChangeDropFrame,
  onChangeWaypointAxis,
  onChangeWaypointFrame,
  onChangeJogFrame,
  onJogMove,
  onRecordGrab,
  onRecordDrop,
  onRecordWaypoint,
  showAddWaypoint = true,
}) {
  // Keep a unified initial layout across all assembly blocks.
  const showJoggingPanel = false
  const isSecondBlock = stage === 'second-block'
  const isThirdBlock = stage === 'third-block'
  const confirmButtonLabel = hasSingularityWarning ? 'Reset the robot' : 'Confirm & Test'
  const showSecondBlockHintEntry = isSecondBlock && hasCollision && !isAssemblyRunning
  const showSingularityHintEntry = isThirdBlock && hasSingularityWarning && !isAssemblyRunning
  const showGlobalHintEntry = showSecondBlockHintEntry || showSingularityHintEntry
  const showDirectionErrorFigure =
    collisionHintType === 'direction' && hasCollision && !isAssemblyRunning
  const cardTitle = isThirdBlock
    ? 'Assemble the third block'
    : isSecondBlock
      ? 'Assemble the second block'
      : 'Assemble the first block'
  const cardSequenceNumber = isThirdBlock ? '3' : isSecondBlock ? '2' : '1'
  const cardImageSrc = showDirectionErrorFigure
    ? mediaAssets.assemblyDirectionErrorFigure
    : isThirdBlock
      ? '/media/assembly-lion-hint-third.png'
      : isSecondBlock
        ? '/media/assembly-lion-hint-second.png'
        : '/media/assembly-lion-hint.jpg'

  return (
    <PageLayout>
      <div className="flex items-center justify-between shrink-0 mb-10">
        <div className="assembly-page-title px text-[24px]">
          Lion Model Assembly Game
        </div>
        <div className="flex items-center gap-3">
          <ConnectionStatusLabel text={connectionInfo} />
          <ResetArmButton />
          <button
            type="button"
            className="connection-pill px text-[9px] px-2 py-2 cursor-pointer select-none hover:brightness-[0.97] active:translate-x-[1px] active:translate-y-[1px] active:shadow-[2px_2px_0_var(--shadow)]"
            onClick={onEnableTeach}
          >
            Enable
          </button>
          <div className="swatch" style={{ background: 'var(--bgPurple)' }} />
          <div className="swatch" style={{ background: 'var(--orange)' }} />
          <div className="swatch" style={{ background: 'var(--magenta)' }} />
        </div>
      </div>

      <StepBar steps={steps} />

      <PixelToast
        open={showCollisionToast}
        icon="⚠"
        message="Collision occurred! Try to solve it"
      />

      <div className="grid max-lg:grid-cols-1 max-lg:[grid-auto-rows:max-content] max-lg:flex-none gap-8 lg:grid-cols-[4fr_3fr] lg:flex-1 lg:min-h-0">
        <PixelCard
          padding="p-6"
          className="flex min-h-0 max-h-full flex-col overflow-hidden max-lg:max-h-none"
        >
          <div className="flex min-h-0 flex-1 flex-col gap-4 overflow-y-auto pr-4 pb-6 max-lg:min-h-min max-lg:flex-none max-lg:overflow-visible">
            <div className="assembly-intro assembly-intro-prominent assembly-trajectory-title text-[20px] leading-[1.2] font-bold">
              Drag the robot&apos;s end effector to teach it where to pick and place the
              block.
            </div>

            {showJoggingPanel ? (
              <div
                className={`pixel-card soft-grid mt-2 p-3 ${
                  hasSingularityWarning ? 'assembly-danger-shell' : ''
                }`}
                style={{ background: 'var(--panel)' }}
              >
                <div className="flex items-center justify-between gap-4 mb-2">
                  <div className="assembly-ink text-[22px]">
                    Jogging
                  </div>
                  <PixelSelect
                    className="w-[220px]"
                    value={jogFrame}
                    onChange={onChangeJogFrame}
                    options={jogFrameOptions}
                    variant="flat"
                  />
                </div>
                <div className="grid grid-cols-2 gap-3">
                  <JogAxisControl
                    label="X"
                    onNegative={() => onJogMove('x', 'negative')}
                    onPositive={() => onJogMove('x', 'positive')}
                  />
                  <JogAxisControl
                    label="Z"
                    onNegative={() => onJogMove('z', 'negative')}
                    onPositive={() => onJogMove('z', 'positive')}
                  />
                  <JogAxisControl
                    label="Y"
                    onNegative={() => onJogMove('y', 'negative')}
                    onPositive={() => onJogMove('y', 'positive')}
                  />
                  <JogAxisControl
                    label="Rx"
                    onNegative={() => onJogMove('rx', 'negative')}
                    onPositive={() => onJogMove('rx', 'positive')}
                  />
                </div>
              </div>
            ) : null}

            <PixelCard
              padding="p-4"
              className={`flex min-h-0 flex-1 overflow-visible assembly-trajectory-shell max-lg:flex-none max-lg:min-h-min ${
                hasSingularityWarning ? 'assembly-danger-shell' : ''
              }`}
            >
              <div
                className="assembly-trajectory-scroll flex min-h-0 flex-1 flex-col gap-3 overflow-y-auto max-lg:min-h-min max-lg:flex-none max-lg:overflow-visible"
              >
                <TrajectoryPointCard
                  accent="magenta"
                  title="Pick Point"
                  point={grab}
                  frameOptions={frameOptions}
                  frameValue={grabFrame}
                  onFrameChange={onChangeGrabFrame}
                  onAxisChange={onChangeGrabAxis}
                  onRecord={onRecordGrab}
                />

                {waypoints.map((waypoint) => (
                  <TrajectoryPointCard
                    key={waypoint.id}
                    accent="orange"
                    title="WayPoint"
                    point={waypoint.point}
                    frameOptions={frameOptions}
                    frameValue={waypoint.frame}
                    onFrameChange={(value) =>
                      onChangeWaypointFrame(waypoint.id, value)
                    }
                    onAxisChange={(axis, value) =>
                      onChangeWaypointAxis(waypoint.id, axis, value)
                    }
                    onRecord={() => onRecordWaypoint(waypoint.id)}
                    onRemove={() => onRemoveWaypoint(waypoint.id)}
                  />
                ))}

                {showAddWaypoint && (
                  <div className="my-2 flex justify-center">
                    <button
                      type="button"
                      onClick={onAddWaypoint}
                      className="waypoint-pixel-circle-btn waypoint-pixel-circle-btn--add waypoint-pixel-circle-btn--img px"
                      aria-label="Add waypoint"
                    >
                      <img
                        src="/icons/waypoint-add.png"
                        alt=""
                        className="waypoint-action-icon waypoint-action-icon--add"
                        draggable={false}
                      />
                    </button>
                  </div>
                )}

                <TrajectoryPointCard
                  accent="green"
                  title="Drop Point"
                  point={drop}
                  frameOptions={frameOptions}
                  frameValue={dropFrame}
                  onFrameChange={onChangeDropFrame}
                  onAxisChange={onChangeDropAxis}
                  onRecord={onRecordDrop}
                  bordered={false}
                />
              </div>
            </PixelCard>
          </div>

          <div className="mt-4 flex items-center gap-4">
            {isAssemblyRunning ? (
              <div
                className="assembly-running-shell w-full"
              >
                <div className="running-bar assembly-running-fill" />
                <span className="assembly-running-label px text-[13px]">
                  Running...
                </span>
              </div>
            ) : (
              <>
                <PixelButton
                  variant="white"
                  className={`assembly-mode-pixel-btn py-4 px-8 text-[14px] ${
                    mode === 'pick' ? 'assembly-mode-btn-pick' : 'assembly-mode-btn-drop'
                  }`}
                  onClick={onToggleMode}
                >
                  {mode === 'pick' ? 'Pick' : 'Drop'}
                </PixelButton>
                <PixelButton
                  variant="magenta"
                  className={`flex-1 py-4 text-[12px] ${
                    !canConfirm ? 'opacity-40 pointer-events-none' : ''
                  }`}
                  disabled={!canConfirm}
                  onClick={onConfirmTest}
                >
                  {confirmButtonLabel}
                </PixelButton>
              </>
            )}
          </div>
        </PixelCard>

        <PixelCard
          title={cardTitle}
          titleColor="var(--orange)"
          titleBadgeText={cardSequenceNumber}
          className="flex min-h-0 max-h-full flex-col overflow-hidden max-lg:max-h-none"
        >
          <div className="assembly-model-stage flex min-h-0 flex-1 overflow-hidden max-lg:min-h-[min(52vh,340px)] max-lg:flex-none">
            <div
              className={`assembly-lion-hint-frame flex-1 min-h-0 w-full ${
                isThirdBlock ? 'assembly-lion-hint-frame--natural' : ''
              }`}
            >
              {showSingularityHintEntry && (
                <div className="assembly-singularity-top-hint">
                  You can move the block to avoid the singularity on the trajectory.
                </div>
              )}
              <img
                src={cardImageSrc}
                alt=""
                className={`assembly-lion-hint-img ${
                  isThirdBlock ? 'assembly-lion-hint-img--natural' : ''
                } ${showDirectionErrorFigure ? 'assembly-lion-hint-img--direction-error' : ''}`}
                draggable={false}
              />
              {showGlobalHintEntry && (
                <button
                  type="button"
                  onClick={onOpenCollisionHint}
                  className="assembly-collision-hint-fab"
                  aria-label="Open collision hint"
                >
                  <span className="assembly-collision-hint-fab-icon">💡</span>
                </button>
              )}
            </div>
          </div>
        </PixelCard>
      </div>

      {showSuccessModal && (
        <div
          className="assembly-modal-overlay fixed inset-0 z-50 flex items-center justify-center"
        >
          <div className="w-full max-w-xl px-6">
            <div className="text-center">
              <CelebrationImage
                frameClassName="assembly-modal-gif mx-auto mb-6"
                imageClassName="assembly-modal-gif-image"
                alt="Celebration"
              />
              <div className="assembly-success-text px text-[20px] mb-3">
                Assembly complete!
              </div>
              <div className="assembly-success-text px text-[20px] mb-8">
                {successSubline}
              </div>
              <div className="flex items-center gap-4">
                <PixelButton
                  variant="white"
                  className="px-8 py-5 text-[12px]"
                  onClick={onTryAgainCurrentBlock}
                >
                  Try again
                </PixelButton>
                <PixelButton
                  variant="magenta"
                  className="flex-1 py-5 text-[14px]"
                  onClick={onSuccessPrimaryAction ?? onNextBlock}
                >
                  {successPrimaryLabel ?? 'Next block'}
                </PixelButton>
              </div>
            </div>
          </div>
        </div>
      )}

      {showCollisionHintModal && (
        <CollisionHintModal
          hintType={collisionHintType}
          hintStep={collisionHintStep}
          showWrongAnswerToast={showWrongAnswerToast}
          selectedOption={selectedCollisionOption}
          onSelectOption={onSelectCollisionOption}
          onClose={onCloseCollisionHint}
          onConfirm={onConfirmCollisionHint}
        />
      )}
    </PageLayout>
  )
}
